services:
  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
    volumes:
      - ./apps/server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npx prisma generate && npx prisma db push --force-reset && npm run dev"
    stop_grace_period: 30s

  frontend:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "5173:5173"
    volumes: 
      - ./apps/client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    depends_on:
      - backend
    tty: true
    stdin_open: true
volumes:
  pgdata: